import PDFDocument from "pdfkit";
import type { GeneratedReport } from "@/engine/types/ai";

const BOLT_GREEN = "#34D186";
const INK = "#1A1A1A";
const MUTED = "#6C7070";

export interface ReportPdfMeta {
  report: GeneratedReport;
  reference: string;
  marketCountry: string;
  regulator: string;
  generatedAt: string;
  elapsedMs?: number | null;
  model?: string | null;
}

function substituteFigures(body: string, report: GeneratedReport): string {
  return body.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const f = report.figures.find((x) => x.fieldKey === key);
    return f ? String(f.value) : `{{${key}}}`;
  });
}

export function renderReportPdf(meta: ReportPdfMeta): Promise<Buffer> {
  const { report } = meta;
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 56 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const left = 56;
    const width = doc.page.width - left * 2;

    // Bolt Sentinel header
    doc.rect(0, 0, doc.page.width, 6).fill(BOLT_GREEN);
    // bolt mark (angular zigzag)
    doc.save().translate(left, 30).fillColor(BOLT_GREEN);
    doc.moveTo(13, 0).lineTo(2, 13).lineTo(8, 13).lineTo(6, 24).lineTo(18, 9).lineTo(11, 9).fill();
    doc.restore();
    doc.fillColor(INK).font("Helvetica-Bold").fontSize(15).text("Bolt Sentinel", left + 26, 32);
    doc.fillColor(MUTED).font("Helvetica").fontSize(9).text(`${meta.regulator} · ${meta.marketCountry}`, left + 26, 50);
    doc.fillColor(MUTED).fontSize(9).text(`Ref ${meta.reference}`, left, 32, { width, align: "right" });

    let y = 84;
    doc.fillColor(INK).font("Helvetica-Bold").fontSize(16).text(report.title, left, y, { width });
    y = doc.y + 8;
    doc.fillColor(INK).font("Helvetica").fontSize(10).text(report.preamble, left, y, { width });
    y = doc.y + 14;

    for (const section of report.sections) {
      if (y > doc.page.height - 160) {
        doc.addPage();
        y = 70;
      }
      doc.fillColor(BOLT_GREEN).font("Helvetica-Bold").fontSize(11).text(section.heading.toUpperCase(), left, y, { width });
      y = doc.y + 4;
      doc.fillColor(INK).font("Helvetica").fontSize(10).text(substituteFigures(section.body, report), left, y, { width });
      y = doc.y + 12;
    }

    // figures table
    if (report.figures.length) {
      if (y > doc.page.height - 200) {
        doc.addPage();
        y = 70;
      }
      doc.fillColor(BOLT_GREEN).font("Helvetica-Bold").fontSize(11).text("REPORTED FIGURES", left, y, { width });
      y = doc.y + 6;
      for (const f of report.figures) {
        doc.fillColor(MUTED).font("Helvetica").fontSize(9).text(f.label, left, y, { width: width * 0.7 });
        doc.fillColor(INK).font("Helvetica-Bold").fontSize(10).text(`${f.value}${f.unit ? " " + f.unit : ""}`, left + width * 0.7, y, { width: width * 0.3, align: "right" });
        y += 18;
      }
      y += 6;
    }

    doc.fillColor(INK).font("Helvetica").fontSize(10).text(report.closing, left, y, { width });

    // footer
    const fy = doc.page.height - 84;
    doc.moveTo(left, fy).lineTo(left + width, fy).strokeColor("#E5E5E5").stroke();
    doc.fillColor(MUTED).font("Helvetica").fontSize(8).text(
      `Generated by Bolt Sentinel on ${meta.generatedAt}${meta.elapsedMs ? ` · pipeline ${(meta.elapsedMs / 1000).toFixed(1)}s` : ""}${meta.model ? ` · ${meta.model}` : ""}. Synthetic demonstration data — not an official filing.`,
      left,
      fy + 10,
      { width },
    );
    doc.end();
  });
}
